global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: [ 'localhost:9090' ]

  - job_name: 'ads_service'
    metrics_path: /api/metrics
    static_configs:
      - targets: [ 'ads_service:9091' ]

  - job_name: 'auth_service'
    metrics_path: /api/metrics
    static_configs:
      - targets: [ 'auth_service:9092' ]

  - job_name: 'city_service'
    metrics_path: /api/metrics
    static_configs:
      - targets: [ 'city_service:9093' ]

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']
  - job_name: 'main_backend'

    metrics_path: /api/metrics
    static_configs:
      - targets: [ 'backend:8008' ]