// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package domain

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson896ef83dDecode20242FIGHTCLUBDomain(in *jlexer.Lexer, out *VisitedRegionsList) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		in.Skip()
		*out = nil
	} else {
		in.Delim('[')
		if *out == nil {
			if !in.IsDelim(']') {
				*out = make(VisitedRegionsList, 0, 0)
			} else {
				*out = VisitedRegionsList{}
			}
		} else {
			*out = (*out)[:0]
		}
		for !in.IsDelim(']') {
			var v1 VisitedRegions
			(v1).UnmarshalEasyJSON(in)
			*out = append(*out, v1)
			in.WantComma()
		}
		in.Delim(']')
	}
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson896ef83dEncode20242FIGHTCLUBDomain(out *jwriter.Writer, in VisitedRegionsList) {
	if in == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v2, v3 := range in {
			if v2 > 0 {
				out.RawByte(',')
			}
			(v3).MarshalEasyJSON(out)
		}
		out.RawByte(']')
	}
}

// MarshalJSON supports json.Marshaler interface
func (v VisitedRegionsList) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson896ef83dEncode20242FIGHTCLUBDomain(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v VisitedRegionsList) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson896ef83dEncode20242FIGHTCLUBDomain(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *VisitedRegionsList) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson896ef83dDecode20242FIGHTCLUBDomain(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *VisitedRegionsList) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson896ef83dDecode20242FIGHTCLUBDomain(l, v)
}
func easyjson896ef83dDecode20242FIGHTCLUBDomain1(in *jlexer.Lexer, out *VisitedRegions) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = int(in.Int())
		case "name":
			out.Name = string(in.String())
		case "userId":
			out.UserID = string(in.String())
		case "startVisitDate":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.StartVisitDate).UnmarshalJSON(data))
			}
		case "endVisitDate":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.EndVisitDate).UnmarshalJSON(data))
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson896ef83dEncode20242FIGHTCLUBDomain1(out *jwriter.Writer, in VisitedRegions) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.ID))
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"userId\":"
		out.RawString(prefix)
		out.String(string(in.UserID))
	}
	{
		const prefix string = ",\"startVisitDate\":"
		out.RawString(prefix)
		out.Raw((in.StartVisitDate).MarshalJSON())
	}
	{
		const prefix string = ",\"endVisitDate\":"
		out.RawString(prefix)
		out.Raw((in.EndVisitDate).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v VisitedRegions) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson896ef83dEncode20242FIGHTCLUBDomain1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v VisitedRegions) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson896ef83dEncode20242FIGHTCLUBDomain1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *VisitedRegions) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson896ef83dDecode20242FIGHTCLUBDomain1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *VisitedRegions) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson896ef83dDecode20242FIGHTCLUBDomain1(l, v)
}
