name: Build, Lint, Test, and Push Services

on:
  push:
    branches:
      - dev

jobs:
  build-lint-test-and-push:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up Go
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      # 3. Install dependencies
      - name: Install Go dependencies
        run: |
          go mod tidy
          go mod download

      # 4. Install golangci-lint
      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.54.2

      # 5. Run linter
      - name: Run golangci-lint
        run: |
          golangci-lint run

      # 6. Run tests
      - name: Run Go tests
        run: |
          go test -coverpkg=./... -coverprofile=cover ./... && cat cover | grep -v "mock" | grep -v  "easyjson" | grep -v "proto" | grep -v "pb" > cover.out && go tool cover -func=cover.out

      # 7. Login to DockerHub
      - name: Login to DockerHub Registry
        run: echo ${{secrets.DOCKERHUB_TOKEN}} | docker login -u ${{secrets.DOCKERHUB_USERNAME}} --password-stdin

      # 8. Build ads_service
      - name: Build and push ads_service
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./microservices/ads_service/Dockerfile
          tags: ${{secrets.DOCKERHUB_USERNAME}}/ads_service:latest
          push: true

      # 9. Build auth_service
      - name: Build and push auth_service
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./microservices/auth_service/Dockerfile
          tags: ${{secrets.DOCKERHUB_USERNAME}}/auth_service:latest
          push: true

      # 10. Build city_service
      - name: Build and push city_service
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./microservices/city_service/Dockerfile
          tags: ${{secrets.DOCKERHUB_USERNAME}}/city_service:latest
          push: true

      # 11. Build migrator
      - name: Build and push migrator
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./cmd/migrator/Dockerfile
          tags: ${{secrets.DOCKERHUB_USERNAME}}/migrator:latest
          push: true

      # 12. Build backend (main service)
      - name: Build and push backend
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          tags: ${{secrets.DOCKERHUB_USERNAME}}/backend:latest
          push: true
