name: Build and Deploy Microservices

on:
    push:
        branches: ["deploy"]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code and build on server
              uses: appleboy/ssh-action@master
              with:
                  host: 37.139.41.110
                  username: ubuntu
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  script: |
                      cd ~
                      sudo git clone ${{ github.server_url }}/${{ github.repository }} backend/
                      cd backend/
                      git switch dev
                      sudo docker compose build --no-cache
                      sudo docker compose up -d --remove-orphans
