name: Build and Deploy Microservices

on:
    push:
        branches: ["deploy"]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Install rsync
              run: sudo apt-get update && sudo apt-get install -y rsync
            - name: Copy code to server using rsync
              uses: appleboy/ssh-action@master
              with:
                  host: 37.139.41.110
                  username: ubuntu
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  script: |
                      rsync -avz -e "ssh -p 22" ./ ubuntu@37.139.41.110:/opt/backend-deploy/
            - name: Build and deploy on server
              uses: appleboy/ssh-action@master
              with:
                  host: 37.139.41.110
                  username: ubuntu
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  script: |
                      sudo apt update && sudo apt install -y docker.io docker-compose
                      cd /opt/backend-deploy/
                      sudo docker-compose build --no-cache
                      sudo docker-compose up -d --remove-orphans
