name: Build and Deploy Microservices

on:
    push:
        branches: ["deploy"]

jobs:
    build-test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up Docker
              uses: docker/setup-buildx-action@v2
            - name: Build all Docker images (test build)
              run: docker compose build --progress=plain --no-cache
            - name: Test docker images
              run: docker images -a
    deploy:
        runs-on: ubuntu-latest
        needs: build-test
        steps:
            - name: Checkout code and build on server
              uses: appleboy/ssh-action@master
              with:
                  host: 37.139.41.110
                  username: ubuntu
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  script: |
                      cd /opt/backend-deploy
                      git init
                      git remote add origin ${{ github.server_url }}/${{ github.repository }}
                      git fetch origin ${{ github.ref }}
                      git reset --hard origin/${{ github.ref }}
                      sudo docker compose build --no-cache
                      sudo docker compose up -d --remove-orphans
