name: Build and Deploy Microservices

on:
    push:
        branches: ["deploy"]

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Copy context to server
              uses: burnettk/rsync-deployments@5.2
              with:
                  switches: -avz --delete
                  path: .
                  remote_destination: ubuntu@37.139.41.110:/opt/backend-deploy/
                  remote_host: 37.139.41.110
                  private_key: ${{ secrets.SSH_PRIVATE_KEY }}

            - name: Build and deploy on server
              uses: appleboy/ssh-action@master
              with:
                  host: 37.139.41.110
                  username: ubuntu
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  script: |
                      cd /opt/backend-deploy/
                      sudo docker-compose pull # Pull latest images if you are using a registry
                      sudo docker-compose build --no-cache # Build services
                      sudo docker-compose up -d --remove-orphans # Start services in detached mode
