name: Build and Deploy Microservices

on:
    push:
        branches: ["deploy"]

jobs:
    deploy:
        runs-on: ubuntu-latest
        needs: build-test
        steps:
            - name: Checkout code and build on server
              uses: appleboy/ssh-action@master
              with:
                  host: 37.139.41.110
                  username: ubuntu
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  script: |
                      cd /opt/backend-deploy
                      git init
                      git remote add origin ${{ github.server_url }}/${{ github.repository }}
                      git fetch origin ${{ github.ref }}
                      git reset --hard origin/${{ github.ref }}
                      sudo docker compose build --no-cache
                      sudo docker compose up -d --remove-orphans
