name: Build, Lint, Test, and Push Services

on:
  push:
    branches:
      - dev

jobs:
  build-lint-test-and-push:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Run linter
      - name: Run golangci-lint
        run: |
          golangci-lint run

      # 3. Run tests
      - name: Run Go tests
        run: |
          go test -coverpkg=./... -coverprofile=cover ./... && cat cover | grep -v "mock" | grep -v  "easyjson" | grep -v "proto" | grep -v "pb" > cover.out && go tool cover -func=cover.out

      # 4. Login to DockerHub
      - name: Login to DockerHub Registry
        run: echo ${{secrets.DOCKERHUB_TOKEN}} | docker login -u ${{secrets.DOCKERHUB_USERNAME}} --password-stdin

      # 5. Build ads_service
      - name: Build and push ads_service
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./microservices/ads_service/Dockerfile
          tags: ${{secrets.DOCKERHUB_USERNAME}}/ads_service:latest
          push: true

      # 6. Build auth_service
      - name: Build and push auth_service
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./microservices/auth_service/Dockerfile
          tags: ${{secrets.DOCKERHUB_USERNAME}}/auth_service:latest
          push: true

      # 7. Build city_service
      - name: Build and push city_service
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./microservices/city_service/Dockerfile
          tags: ${{secrets.DOCKERHUB_USERNAME}}/city_service:latest
          push: true

      # 8. Build migrator
      - name: Build and push migrator
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./cmd/migrator/Dockerfile
          tags: ${{secrets.DOCKERHUB_USERNAME}}/migrator:latest
          push: true

      # 9. Build backend (main service)
      - name: Build and push backend
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          tags: ${{secrets.DOCKERHUB_USERNAME}}/backend:latest
          push: true
