name: Build and push services

on: [push, pull_request]

jobs:
    linter:
        name: lint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-go@v4
              with:
                  go-version: "1.22.0"
                  cache: false
            - name: golangci-lint
              uses: golangci/golangci-lint-action@v3
              with:
                  version: v1.53
                  args: --timeout=5m
