name: SSH Test
on: push
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: SSH Connection
              uses: appleboy/ssh-action@master
              with:
                  host: 37.139.41.110
                  username: ubuntu
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  script: echo "Connected"
